platform :ios, "14.0"
use_frameworks!

target 'Swerkin_Example' do

  target 'Swerkin-UnitTests' do
    inherit! :search_paths
    inhibit_all_warnings!

    pod 'Swerkin', :path => '../'
  end
  
  target 'Swerkin-UITests' do
    inherit! :search_paths
    inhibit_all_warnings!

    pod 'Swerkin', :path => '../'
    pod 'KIF', :git => 'https://github.com/kif-framework/KIF.git', :branch => 'master'
    pod 'KIF/IdentifierTests', :git => 'https://github.com/kif-framework/KIF.git', :branch => 'master'

  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
